from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 400)
        MainWindow.setMinimumSize(QtCore.QSize(490, 400))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(90, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(180, 142, 205);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.Btn_Toggle.setFont(font)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(90, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(90, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_1.sizePolicy().hasHeightForWidth())
        self.btn_page_1.setSizePolicy(sizePolicy)
        self.btn_page_1.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_2.sizePolicy().hasHeightForWidth())
        self.btn_page_2.setSizePolicy(sizePolicy)
        self.btn_page_2.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_3.sizePolicy().hasHeightForWidth())
        self.btn_page_3.setSizePolicy(sizePolicy)
        self.btn_page_3.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_page = QtWidgets.QFrame(self.Content)
        self.frame_page.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_page.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_page.setObjectName("frame_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.formLayoutWidget = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMinimumSize(QtCore.QSize(150, 19))
        self.label_1.setMaximumSize(QtCore.QSize(150, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(85, 85, 127);")
        self.label_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_1.setScaledContents(False)
        self.label_1.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_1.setWordWrap(False)
        self.label_1.setOpenExternalLinks(False)
        self.label_1.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.spinBox_1 = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_1.setFont(font)
        self.spinBox_1.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                     "color: rgb(255, 255, 255);")
        self.spinBox_1.setObjectName("spinBox_1")
        self.gridLayout.addWidget(self.spinBox_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 19))
        self.label_2.setMaximumSize(QtCore.QSize(150, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(85, 85, 127);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                     "color: rgb(255, 255, 255);")
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(150, 19))
        self.label_3.setMaximumSize(QtCore.QSize(150, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(85, 85, 127);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                     "color: rgb(255, 255, 255);")
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.btn_save_1 = QtWidgets.QPushButton(self.page_1)
        self.btn_save_1.setGeometry(QtCore.QRect(310, 100, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_save_1.setFont(font)
        self.btn_save_1.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_save_1.setObjectName("bth_save_1")
        self.line = QtWidgets.QFrame(self.page_1)
        self.line.setGeometry(QtCore.QRect(10, 130, 371, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btn_save_2 = QtWidgets.QPushButton(self.page_1)
        self.btn_save_2.setGeometry(QtCore.QRect(320, 310, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_save_2.setFont(font)
        self.btn_save_2.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_save_2.setObjectName("btn_save_2")
        self.line_2 = QtWidgets.QFrame(self.page_1)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 371, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 232, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(232, 19))
        self.label_4.setMaximumSize(QtCore.QSize(232, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(85, 85, 127);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)

        # table_1 for employees_per_shift
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)

        # self.tableWidget.setRowCount(20)
        # self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.horizontalHeader().setVisible(False)
        # self.tableWidget.setColumnWidth(0, 200)
        # self.tableWidget.setFont(font)
        # self.tableWidget.setStyleSheet("color: rgb(255, 255, 255)")
        # self.tableWidget.verticalHeader().setStyleSheet("color: rgb(0, 0, 0)")
        # self.tableWidget.verticalHeader().setSectionResizeMode()

        self.verticalLayout_7.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page_1)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 10, 380, 301))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.btn_save_3 = QtWidgets.QPushButton(self.page_2)
        self.btn_save_3.setGeometry(QtCore.QRect(240, 320, 73, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_save_3.setFont(font)
        self.btn_save_3.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_save_3.setObjectName("btn_save_3")
        self.btn_save_4 = QtWidgets.QPushButton(self.page_2)
        self.btn_save_4.setGeometry(QtCore.QRect(320, 320, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_save_4.setFont(font)
        self.btn_save_4.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_save_4.setObjectName("btn_save_4")
        self.stackedWidget.addWidget(self.page_2)

        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 10, 380, 301))
        self.tableWidget_3.setObjectName("tableWidget_3")

        self.btn_save_5 = QtWidgets.QPushButton(self.page_3)
        self.btn_save_5.setGeometry(QtCore.QRect(320, 320, 50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_save_5.setFont(font)
        self.btn_save_5.setStyleSheet("QPushButton {    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(148, 117, 169);\n"
                                      "}")
        self.btn_save_5.setObjectName("btn_save_5")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_page)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "МЕНЮ"))
        self.btn_page_1.setText(_translate("MainWindow", "КОЛИЧЕСТВО"))
        self.btn_page_2.setText(_translate("MainWindow", "СПИСОК"))
        self.btn_page_3.setText(_translate("MainWindow", "РЕЗУЛЬТАТ"))
        self.label_1.setText(_translate("MainWindow", "Сотрудников:"))
        self.label_2.setText(_translate("MainWindow", "Смен в день:"))
        self.label_3.setText(_translate("MainWindow", "Рабочих дней:"))
        self.btn_save_1.setText(_translate("MainWindow", "ДАЛЕЕ"))
        self.btn_save_2.setText(_translate("MainWindow", "ДАЛЕЕ"))
        self.label_4.setText(_translate("MainWindow", "№ Cмены  | Cотрудников"))
        self.btn_save_3.setText(_translate("MainWindow", "СОХРАНИТЬ"))
        self.btn_save_4.setText(_translate("MainWindow", "ДАЛЕЕ"))
        self.btn_save_5.setText(_translate("MainWindow", "В ФАЙЛ"))
